version: '3.9'

services:
  db:
    image: library/mysql:latest
    container_name: yoon-mysql # 컨테이너 이름
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "django"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "django"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # - /Users/u1/datadir:/var/lib/mysql
      # - /home/u1/project1/helloworld:/:/home/ul/mysql
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  web:
    image: 192.168.1.110:9091/helloworld
    # build: .
    container_name: main_django
    command: hypercorn helloworld.asgi:application -b 0.0.0.0 -p 8000 -w 2
    volumes:
      - ./config:/srv/code
    ports: 
      - "8000:8000"
    depends_on: 
      - db
